-- ====================================================================
-- OLIVE GARDENS SCHEMA UPDATE: MANAGERS, UPLOADS & REALTIME ENABLEMENT
-- ====================================================================
-- Run this script inside your Supabase SQL Editor (https://supabase.com)
-- to create the managers tracking table, uploads history table, and enable real-time.

-- 1. Create the managers table for device-independent accounts
CREATE TABLE IF NOT EXISTS public.managers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'User',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed the initial managers with their custom emails if they don't already exist
INSERT INTO public.managers (email, password, name, role)
VALUES 
  ('tendai.murisa@gmail.com', 'owner123', 'Owner', 'Owner'),
  ('murisa.mzime@gmail.com', 'wife123', 'Wife', 'Co-Manager'),
  ('thunbele004@gmail.com', 'prog123', 'Programmer', 'Developer')
ON CONFLICT (email) DO NOTHING;

-- Configure Row Level Security (RLS) for the managers table
ALTER TABLE public.managers ENABLE ROW LEVEL SECURITY;

-- Safely recreate policies by dropping them if they exist first
DROP POLICY IF EXISTS "Allow public read access managers" ON public.managers;
CREATE POLICY "Allow public read access managers" 
ON public.managers FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert access managers" ON public.managers;
CREATE POLICY "Allow public insert access managers" 
ON public.managers FOR INSERT 
WITH CHECK (true);

-- 2. Create the uploads table
CREATE TABLE IF NOT EXISTS public.uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    row_count INTEGER NOT NULL,
    file_hash TEXT UNIQUE NOT NULL
);

-- Configure Row Level Security (RLS) for the uploads table
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;

-- Safely recreate policies by dropping them if they exist first
DROP POLICY IF EXISTS "Allow public read access uploads" ON public.uploads;
CREATE POLICY "Allow public read access uploads" 
ON public.uploads FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert access uploads" ON public.uploads;
CREATE POLICY "Allow public insert access uploads" 
ON public.uploads FOR INSERT 
WITH CHECK (true);

-- 3. Enable Realtime Publications
-- Add transactions, units, managers, and uploads tables to the supabase_realtime publication
-- to push changes to connected clients in real-time.
DO $$
BEGIN
  -- Add transactions table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'transactions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;
  END IF;

  -- Add units table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'units'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.units;
  END IF;

  -- Add managers table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'managers'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.managers;
  END IF;

  -- Add uploads table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'uploads'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.uploads;
  END IF;
END $$;
