-- ====================================================================
-- OLIVE GARDENS SCHEMA UPDATE: UPLOADS TABLE & REALTIME ENABLEMENT
-- ====================================================================
-- Run this script inside your Supabase SQL Editor (https://supabase.com)
-- to create the uploads tracking table and enable real-time updates.

-- 1. Create the uploads table
CREATE TABLE IF NOT EXISTS public.uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    row_count INTEGER NOT NULL,
    file_hash TEXT UNIQUE NOT NULL
);

-- 2. Configure Row Level Security (RLS) for the uploads table
-- Allows reads and writes to be accessible with your anonymous/publishable keys
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON public.uploads FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert access" 
ON public.uploads FOR INSERT 
WITH CHECK (true);

-- 3. Enable Realtime Publications
-- Add transactions, units, and uploads tables to the supabase_realtime publication
-- to push changes to connected clients in real-time.
BEGIN;
  -- Remove existing tables from publication if already there to avoid duplicates
  ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.transactions;
  ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.units;
  ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.uploads;

  -- Add tables to realtime publication
  ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.units;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.uploads;
COMMIT;
