-- ====================================================================
-- OLIVE GARDENS SCHEMA UPDATE: UPLOADS TABLE & REALTIME ENABLEMENT
-- ====================================================================
-- Run this script inside your Supabase SQL Editor (https://supabase.com)
-- to create the uploads tracking table and enable real-time updates.

-- 1. Create the uploads table
CREATE TABLE IF NOT EXISTS public.uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    row_count INTEGER NOT NULL,
    file_hash TEXT UNIQUE NOT NULL
);

-- 2. Configure Row Level Security (RLS) for the uploads table
-- Allows reads and writes to be accessible with your anonymous/publishable keys
ALTER TABLE public.uploads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON public.uploads FOR SELECT 
USING (true);

CREATE POLICY "Allow public insert access" 
ON public.uploads FOR INSERT 
WITH CHECK (true);

-- 3. Enable Realtime Publications
-- Add transactions, units, and uploads tables to the supabase_realtime publication
-- to push changes to connected clients in real-time.
DO $$
BEGIN
  -- Add transactions table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'transactions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;
  END IF;

  -- Add units table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'units'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.units;
  END IF;

  -- Add uploads table if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    JOIN pg_publication p ON pr.prpubid = p.oid 
    WHERE p.pubname = 'supabase_realtime' AND c.relname = 'uploads'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.uploads;
  END IF;
END $$;
